apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-credentials
  namespace: mosquitto
type: Opaque
stringData:
  admin-password: himaet23
  # Add additional users as needed
  hima-password: himaet23
