apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: mosquitto
  labels:
    app: mosquitto
spec:
  type: LoadBalancer
  ports:
  - name: mqtt
    port: 1883
    targetPort: mqtt
    protocol: TCP
  - name: mqtts
    port: 8883
    targetPort: mqtts
    protocol: TCP
  - name: websocket
    port: 9001
    targetPort: websocket
    protocol: TCP
  selector:
    app: mosquitto
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-internal
  namespace: mosquitto
  labels:
    app: mosquitto
spec:
  type: ClusterIP
  ports:
  - name: mqtt
    port: 1883
    targetPort: mqtt
    protocol: TCP
  - name: mqtts
    port: 8883
    targetPort: mqtts
    protocol: TCP
  - name: websocket
    port: 9001
    targetPort: websocket
    protocol: TCP
  selector:
    app: mosquitto
